[package]
name = "agent-nft"
version.workspace = true
edition.workspace = true

[dependencies]
soroban-sdk = { version = "20.5.0", features = ["alloc"] }
shared = { path = "../../shared" }

[lib]
crate-type = ["cdylib"]


